### ISSUE TITLE
exposing UUIDs

### ISSUE THREAD

**Issue by progrium** [andreykaipov/goobs#151]
is there a reason why UUIDs (for example, of scenes) aren't exposed? they're in the JSON data.

**Comment by andreykaipov** [comment]
Hey @progrium - are you using an up-to-date version of this library? UUIDs were added in obs-websocket v5.4.0, and the corresponding tag for that in goobs is v1.2.0: https://github.com/andreykaipov/goobs/releases/tag/v1.2.0

**Comment by progrium** [comment]
For which resources? I don't see it for scenes: https://pkg.go.dev/github.com/andreykaipov/goobs@v1.2.3/api/typedefs#Scene

**Comment by andreykaipov** [comment]
Ah I see what you mean now... The structs in that package are manually maintained outside of protocol version updates, so I never actually updated them when the automation ran against the v5.4.0 protocol. 😅 So only requests that had UUID fields declared directly in the protocol were added like this one: https://pkg.go.dev/github.com/andreykaipov/goobs@v1.2.3/api/requests/scenes#GetSceneListResponse.

I added the missing fields in https://github.com/andreykaipov/goobs/pull/152, along with some checks that should hopefully prevent things like this happening in the future. Should be fixed in v1.3.0. Thank you for pointing it out! Please lemme know if you run into anything else.

**Comment by progrium** [comment]
Ah, UUIDs everywhere! Great, thank you for that and this library!
