### ISSUE TITLE
Please drop vendored libraries

### ISSUE THREAD

**Issue by bdrung** [andreykaipov/goobs#26]
I packaged goobs for Debian (see https://tracker.debian.org/pkg/golang-github-andreykaipov-goobs) and had to remove the vendored libraries from the source package (`internal/vendor` and `vendor`). Since you are using `go.mod` can you drop the vendored libraries from the git repository?

**Comment by andreykaipov** [comment]
That's really cool! Thanks for doing that. I'm a bit confused though. Since this is just a library, what's the expected outcome when installing it? Is it just a requirement if one wants to add https://github.com/muesli/obs-cli/ as a package in the future?

As for vendoring dependencies... maybe I'm just stuck in the old ways. I took a quick peek at popular Go projects and a lot don't include the vendor directory anymore. I suppose there's no concern about a dependency being deleted from GitHub if it's cached by the Go proxy, right? I tested it out and I'd be okay with dropping them.

Also, you could technically exclude the `internal` directory entirely. It just generates the API and also excluded when this library is `go get`. Not sure if that makes maintaining the Debian package easier or not.

**Comment by bdrung** [comment]
The Debian source package just produces the development package golang-github-andreykaipov-goobs-dev which can be used as build dependency for other package. It is required for building obs-cli for Debian (see also https://bugs.debian.org/1000489).

Having the dependencies cached should help in case they are deleted from GitHub. For Debian, everything has to be locally available for building. So every needed library needs to be packaged and to access to GitHub is required.

For dropping the `internal` directory entirely, some work is needed. As mentioned above, the package must build without Internet access. So everything needs to be available locally (either in the source package or from the build dependencies). So the obs-websocket Debian package should ship the protocol documentation file and golang-github-andreykaipov-goobs needs to use it from there during build.

**Comment by andreykaipov** [comment]
Sorry for the wait. Released in v0.8.0!

**Comment by bdrung** [comment]
Thanks. Uploaded 0.8.0-1 to Debian unstable.
